### ISSUE TITLE
Vega Support in Juno IDE

### ISSUE THREAD

**Issue by shivaramkrs** [johnmyleswhite/Vega.jl#105]
I asked if it is possible to support Vega in Juno IDE (Atom editor), this is the replay I got. 

> Unfortunately Vega is hard to support in Atom because it uses eval (which is disabled by the security policy).

http://discuss.junolab.org/t/new-features-you-want-in-atom-ide/494/5

I am not an expert at this, I want to know if Vega needs "eval" badly or is it optional? There is a good chance for Juno to become one of the most popular IDEs for Julia.

**Comment by randyzwitch** [comment]
I have nothing against supporting Juno (especially merging in a PR), but the "problem" is a bit opaque to me from the discussion. Valid Julia code comes first, IDE second IMO; nothing in Vega.jl should be non-standard enough to cause security restrictions

**Comment by shivaramkrs** [comment]
I can still use Vega in Juno. It opens up the browser when I evaluate the code. That is fine with me. 

I was looking at different types of charts:
http://vega.github.io/vega-editor/index.html?mode=vega&spec=parallel_coords&renderer=svg
http://vega.github.io/vega-editor/index.html?mode=vega&spec=force&renderer=svg

They are really good. Can I use them now or will these be available in the future? Do you have any plans for 3d plots?

**Comment by randyzwitch** [comment]
Everything is technically available now, if you map the examples to the Julia types. I'm sure at some point I will add both of those chart types, but it's a matter of time shortage rather than ability/desire at this point. I don't know that base vega.js supports 3D plots; if it does, then it would work in Vega.jl as well.

Hopefully this package can pick up enough where others start to contribute as well...we've had some contributions so far, the base just needs to be broadened further.

**Comment by Balinus** [comment]
Indeed, support in Juno (Atom) would be great. I'm working on a server and firing up firefox is (really) slow. I do like the syntax of Vega, but can't use it effectively.

**Comment by randyzwitch** [comment]
I'll leave this issue open, but the use of `eval` in the package is core functionality. So unless someone can re-write the macro portion of the rendering code, I don't see how this can be implemented.
