### ISSUE TITLE
Can't control number of axis ticks on a heatmap

### ISSUE THREAD

**Issue by ahwillia** [johnmyleswhite/Vega.jl#125]
``` julia
x = Array(Int, 900)
y = Array(Int, 900)
color = Array(Float64, 900)

t = 0
for i in 1:30
    for j in 1:30
        t += 1
        x[t] = i
        y[t] = j
        color[t] = rand()
    end
end

hm = heatmap(x = x, y = y, color = color)
xlab!(hm, title="hello world", ticks=4)
```

Produces the following image (note the number of xticks.... isn't 4):

![download](https://cloud.githubusercontent.com/assets/636625/14518610/d846543a-01cd-11e6-9359-9971333e669d.png)

**Comment by randyzwitch** [comment]
The data generating example is somewhat poor for what is actually happening here. Behind the scenes, I'm using an Vega `ordinal` scale so that all the values are shown; using `ticks` requires a `quantitative` scale, so it has no effect here.

I can't remember the reason at this moment, but the obvious thought of switching the scale types (probably) doesn't work. I'd have to revisit this example to see how this could be fixed.
