### ISSUE TITLE
Supporting "wide-data" in addition to current vector-based data

### ISSUE THREAD

**Issue by ahwillia** [johnmyleswhite/Vega.jl#127]
I'm finding myself writing a lot of matplotlib-style wrapper functions to make plotting easier for me... I am curious if this runs counter to the philosophy of this package. If not, I'd be happy to create a TODO list along these lines and open some pull requests. I understand that there are stylistic choices here -- I'm just curious to understand what the vision is for this package.

For example, I use the following to create a multi-line plot where each sequential pair of columns in `X` and `Y` holds the data for a line.

``` julia
function lineplot(
        X::AbstractMatrix,
        Y::AbstractMatrix;
        kwargs...
    )

    @assert size(X) == size(Y)

    g = [ ind2sub(X,i)[2] for i in eachindex(X) ] # each column is a different group
    Vega.lineplot(x = slice(X,:), y = slice(Y,:), group = g, kwargs...)
end
```

**Comment by tbreloff** [comment]
Alex: in case you don't know about it, I have a package Plots.jl that makes
this sort of stuff simple. If you're considering a PR for a Vega interface,
it would be much cooler/easier if you would consider writing some minimal
link code to support Vega from Plots (or you might find that other backends
fit your needs as well). Sorry about the spam Randy/John... I've been
trying to leave you alone as best I can (sometimes I can't help myself!)

**Comment by randyzwitch** [comment]
@ahwillia It would be great to have "wide data" methods for plain arrays, as well as for DataFrames, I just haven't had time to build it. I tend to work with databases, so "long format" is what has been developed so far. It seems like with a modification of `add_data!` to handle 2-dimensional arrays and switching from `AbstractVector` to `AbstractArray` in the outer function signature might get you what you are after pretty quickly (as opposed to modifying every visualization function). 

The only stylistic choice/vision I have is that each visualization has the minimum number of arguments to create a sane default; that's why many functions only take data arguments. Then, modifications happen via a mutating function on the base `VegaVisualization` type. This is really just because I dislike the grammar-of-graphics style, not because I have something against Gadfly :)

I certainly appreciate any contributions anyone makes, and I hope I haven't given anyone the impression otherwise...the point is not to create a package for just me to use, but one for the community.

**Comment by randyzwitch** [comment]
@tbreloff I don't have any problem with your package, it just doesn't fit my goals. The way I use Vega is for rapid prototyping at work, then I take the generated JSON and use the vega.js library directly in web-based visualizations. So I don't need a common syntax to switch backends, vega.js (or d3.js) is always the backend I want.

That said, if you're not going to improve Vega directly, I'd appreciate it if you didn't try to siphon off people interested in using the package/willing to make contributions here. Your package wouldn't have backends to swap out if people didn't develop them; suggesting a user check out your package because they "might find that other backends fit your needs as well" is in my opinion a pretty aggressive, anti-community move.

**Comment by tbreloff** [comment]
> a pretty aggressive, anti-community move.

Well this is the opposite of my intentions and I'm sorry for that. I'm trying to help consolidate the community so we can all work together.  It's my opinion that having Vega as a backend would be good for Vega, not just Plots.  Not only does it bring a user-base that might not otherwise use the package, but it also brings with it collaborators that will help fill in missing features.  

However, it's extremely clear that this sort of collaboration is not welcomed, so I will un-watch the repo and try to avoid commenting again.

**Comment by randyzwitch** [comment]
@tbreloff It seems as though we might be talking past each other. My apologies for misconstruing your previous comment.

Are you going to be at JuliaCon this year? If so, let's chat then and figure out where our interests overlap. We're both interested in developing Julia instead of some other language and doing visualization, so clearly we've got more in common than difference :)

**Comment by tbreloff** [comment]
> Are you going to be at JuliaCon this year?

Yes!  In fact I'm doing a workshop on Plots and visualization in Julia.

> clearly we've got more in common than difference

Certainly!  I look forward to a chat.
