### ISSUE TITLE
Vega.jl plotting blank in Jupyter Notebook

### ISSUE THREAD

**Issue by gudeser** [johnmyleswhite/Vega.jl#147]
I am using the Vega.jl but something is not working. when I run simple examples described in the documentation it seems that it actually compiles but the output is completely in blank, despite of making a bigger space for the plot.

I have read many issues and try to execute what is suggested by other users but it is not working for me. It seems there has been problems with Windows. I am using Windows.

I appreciate any advice to solve this issue

**Comment by randyzwitch** [comment]
Thanks for reporting. I'm not much of a Windows person, but I'll try and debug this. What version of Julia and Jupyter are you using?

**Comment by gudeser** [comment]
I am using Julia 0.5.0 and Jupyter notebook 4.3.1. The browser I am using for Jupyter notebooks is Chrome.

I could provide any other information you need.

**Comment by randyzwitch** [comment]
If you checkout from master, it should work in Windows (meaning, it did in my VM when I tested a barplot). 

I'm hesitant to tag a release at this point, because there are a lot of deprecations in 0.5 that I haven't had time to fix, and with 0.6 coming out, I'm not sure exactly what I'm going to do yet. Time flies, been almost a year since I opened #130

**Comment by randyzwitch** [comment]
Tagged a new release for METADATA, so this problem should be resolved for future users.
