### ISSUE TITLE
Vega.jl in Escher.jl

### ISSUE THREAD

**Issue by robertfeldt** [johnmyleswhite/Vega.jl#16]
Escher.jl looks nice and Vega2 has some nice iteractivity that we don't get from Gadfly (currently supported by Escher). Any plans/ideas for how to support Vega in Escher?

**Comment by randyzwitch** [comment]
Absolutely! Shashi and I have talked briefly at JuliaCon, and once we convert this package over to using vega2, we'll figure out how to get Escher integration.

**Comment by robertfeldt** [comment]
That's great. I can try to help once you guys get some example code up there of how the connection is made.

**Comment by shashi** [comment]
I have an idea.

So since Vega.js consumes JSON and produces plots, it is possible to make a <vega-plot> custom element http://www.html5rocks.com/en/tutorials/webcomponents/customelements/ which simply has a property called data which is set to the JSON object.

After that `Elem("vega-plot", data=dict)` where dict is the dict form of the vega plot will draw the plot in Escher. Including vega dependencies can be done inside file called Escher/assets/vega.html. and then included using `push!(window.assets, "vega")`. Although at this point I should probably have a way for third party packages like Vega to register asset files from outside. I'll look into how best to do this.

**Comment by shashi** [comment]
Also, something cool to note is that when the plot updates only the minimal diff of the dict is sent over to the UI - efficient in terms of data transfer.

**Comment by mturok** [comment]
@shashi : just so I'm clear, is the suggestion to create a generic "JSON" based web component?

**Comment by randyzwitch** [comment]
@shashi, I agree, this seems more like an Escher 3rd party integration, rather than adding web elements to Vega.jl. That way, Escher is consuming content, and Vega is producing/pushing content.

**Comment by randyzwitch** [comment]
Right now, graphing inline in the Notebook is broken, and Juno not supported either...so might as well make this into a meta-issue.

**Comment by robertfeldt** [comment]
I tried to do a simple vega Escher component, see:

https://github.com/robertfeldt/Escher.jl/commit/3422a8e0a096b9461ad89d32f964734c5ef09eb3

but there are errors, see:

https://github.com/shashi/Escher.jl/issues/1#issuecomment-124576960

**Comment by randyzwitch** [comment]
@shashi, now that I've got this working in Jupyter Notebook and the REPL, and converted all my code to vega2, what do I/we need to do to get Escher integration going? 

Be as specific as possible please (or submit a PR!), I don't know a single thing about Escher :)

**Comment by randyzwitch** [comment]
I'm closing this out, only because after looking at the Escher code, I have no idea what I would need to do. Additionally, the convention seems that you would import Vega, then define a `writemime` function or similar in Escher. 

However, if there is an easy way to modify one of the functions in render.jl, I'd be happy to accept a pull request.
