### ISSUE TITLE
Add/tighten methods for line plot

### ISSUE THREAD

**Issue by randyzwitch** [johnmyleswhite/Vega.jl#32]
~~This is fun...need to either throw error, make into implicit groups, do a summary function of some sort, etc.~~

Edit: Not a bug, but shows need for more explicit method definitions.

```julia
using Vega

x = [1:100; 1:100]
y = [[1:100] + randn(100); 3.0 + 1.5 * [1:100] + randn(100)]
group = [[1 for i in 1:100]; [2 for i in 1:100]]

lineplot(x = x, y = y)
```

![screen shot 2015-09-08 at 2 37 52 pm](https://cloud.githubusercontent.com/assets/2762787/9743998/503cca5c-5637-11e5-86a5-c2caa8444ff2.png)

**Comment by randyzwitch** [comment]
This is unintended, but is this really a "bug"? Meaning, if a user passes a series of `(x,y)` pairs with duplicated `x` values, what should the behavior be? 

Anyone have thoughts here? Throw a warning? Let user see messed up looking graph and figure it out themselves?

**Comment by tbreloff** [comment]
I get deprecation warnings trying to build x/y, so I don't think this is doing what you think it is?  If a user passes you an unsorted x vector, I think the plot you show is the correct plot to display, so no bug.  If however they pass a vector of vectors, then splitting into 2 series is probably more correct.

**Comment by randyzwitch** [comment]
Not sure I'm understanding the data you're passing in...can you show an example of vector of vectors?

**Comment by tbreloff** [comment]
Compare the "Lines" or parametric plot examples vs the "Vectors w/ pluralized args" example [here](https://github.com/tbreloff/Plots.jl/blob/master/docs/gadfly_examples.md) for an idea of what I mean.  A `Vector{Vector}` implies distinct series, while a `Vector{Float64}` implies one series unless explicitly grouped.

**Comment by randyzwitch** [comment]
So in your case, that's just a different API altogether. You're implicitly grouping when multiple vectors are passed in. The example I show above is what happens if you remove the explicit grouping from the current behavior.

So that's the question. If you do lineplot(x = `Vector{Real}`, y = `Vector{Real}`), where x has repeating values, what should the behavior be? It's a data mistake in the case of a single line.

A `Vector{Vector}` method should be added too (your example).

**Comment by tbreloff** [comment]
I disagree that it is a mistake to pass in an x with repeating values.  I do it all the time (again look at the parametric plot example where I draw the infinity symbol).  Gadfly handles this explicitly by allowing you to either pass in a `Geom.line` which resorts the points by the x input, or `Geom.path` which leaves it unsorted.

**Comment by randyzwitch** [comment]
I see what you're saying now. I was implicitly thinking `lineplot = function`, the old vertical line test for a function from grade school :)

So this isn't a bug, but a Vector{Vector} method that calculates groups should be added.

**Comment by tbreloff** [comment]
I still say you shouldn't focus so much on this part of the API... if we implement Vega as a backend to Plots, you'll get a ton of stuff for free.  In order to implement, you basically need to be able to fill in this template (which, for clean backends, is pretty minimal code):

```
immutable [PkgName]Package <: PlottingPackage end
[pkgname]!() = plotter!(:[pkgname])

# ---------------------------------------------------------------------------

function plot(pkg::[PkgName]Package; kw...)
  d = Dict(kw)
  # TODO: create the window/canvas/context that is the plot within the backend (call it `o`)
  # TODO: initialize the plot... title, xlabel, bgcolor, etc
  Plot(o, pkg, 0, d, Dict[])
end


function plot!(::[PkgName]Package, plt::Plot; kw...)
  d = Dict(kw)
  # TODO: add one series to the underlying package
  push!(plt.seriesargs, d)
  plt
end


function Base.display(::[PkgName]Package, plt::Plot)
  # TODO: display/show the plot
end

# -------------------------------

function savepng(::[PkgName]Package, plt::PlottingObject, fn::String; kw...)
  # TODO: save a PNG of the underlying plot/subplot object
end


# -------------------------------

function buildSubplotObject!(::[PkgName]Package, subplt::Subplot)
  # TODO: build the underlying Subplot object.  this is where you might layout the panes within a GUI window, for example
end


function Base.display(::[PkgName]Package, subplt::Subplot)
  # TODO: display/show the Subplot object
end
```

**Comment by randyzwitch** [comment]
To be honest, I'm not sure compatibility with `Plots.jl` is really one of my design goals with this package. I see where you're coming from with thinking about vega/d3 being a back-end to a generic plotting interface, but for me, this is my opportunity to experiment with plotting grammars other than grammar of graphics or generic `plot` methods.

If what I'm doing can be shimmed into what you're doing, that's cool, but the learning of vega/d3 is really what I'm after.

**Comment by tbreloff** [comment]
Ok, fair enough.  I'll stop pestering you then and move Vega to the back of my priority list.

**Comment by randyzwitch** [comment]
I think we have similar goals overall, just that I'm "allergic" to functions with dozens of arguments. So I'm experimenting here with how high level/declarative can one be when doing a plot.

Take the `wordcloud` / `colorscheme!` for example. Like the rest of my plot functions, I'm trying to make the minimum number of arguments to create that style of plot. Then, there are declarative functions that mutate the plot to apply a different color palette to it.

http://johnmyleswhite.github.io/Vega.jl/wordcloud.html

This seems cognitively easier to me to think of a plot that you continuously mutate (or "sculpt" if you will), but I haven't gotten very far with it yet. OTOH, I see `Plots.jl` as a means of handling all common visualization ideas into a single function (which could also be cognitively easier than grammar of graphics).

So same goals maybe, different approaches? I certainly value your input over here, I'm not trying to hoard development to just myself :+1:

**Comment by johnmyleswhite** [comment]
@tbreloff: I don't want to be too presumptuous, but I worry that you're making a poor use of your time working on Plots.jl, especially given that this thread suggests that you'll need other package authors to change their API's to adapt to the API of Plots.jl. That kind of code synchronization seems intractable both socially and technically. I suspect you'll have more impact on Julia if you pick a different project.

**Comment by tbreloff** [comment]
@johnmyleswhite: It's just the opposite... I want package authors to do exactly what they want to do, and I will turn a Plots request into that package's "approach".  Despite the huge differences in plotting packages, in the end they usually overlap functionality by about 90%.  The wordcloud example is a good example of something that you don't see everywhere... I would expect a user to be able to do:

```
using Plots; vega!()
# populate x vec
wordcloud(x, colorscheme=("Spectral", 11))
```

And for something as simple as this, it just ends up mapping to the Vega example, but for other things there is lots and lots of similar functionality that is re-coded by everyone "because they have to support it".  If you try this command with another backend, it would tell you "bummer... that's not supported, but just add Vega and rerun the command".

My goal is to remove the API burden so package authors can focus on producing cool functionality however they want to, and the "101 ways to pass in data/inputs/settings" can be abstracted away.  At the same time, I want to make it dead-simple for new users to be able to experiment with many plotting packages without going through the hassle of learning a new API every time just to plot a line and test it out.

I'm sorry to hear some people don't find my time well spent... I see value in it for myself.  Also, when I said " In order to implement, __you__ basically need to be able to fill in this template..." above, I really mean __I__ need to fill in that template.  It's worked out well so far... I have pretty extensive support for many types of inputs and plots for Gadfly, Immerse, PyPlot, UnicodePlots, and Qwt with bare-minimum required dependencies. Some of these actually have __more__ features than they did before... for example I'm starting to support different marker shapes for Gadfly, which has been an open issue there for a while, but is actually not quite as hard to implement as part of Plots.  I'd say it's already proven to be a successful project... more features and backends will only make it better.

**Comment by randyzwitch** [comment]
Closing in favor of meta issue
