### ISSUE TITLE
Save products of Vega.jl as a PNG figure

### ISSUE THREAD

**Issue by cndesantana** [johnmyleswhite/Vega.jl#40]
It would be great to be able to save things we do with Vega.jl into a figure, doesn't matter the format, actually (PNG, PDF, EPS, TIFF, ...). In my case, I would like to include a wordcloud in a latex manuscript, so EPS, PDF or PNG would be my preferences. 

Thanks!

**Comment by tbreloff** [comment]
My preference is PNG, so if @cndesantana doesn't care, please make that the
priority.

**Comment by cndesantana** [comment]
I agree, no problem! ;)

**Comment by johnmyleswhite** [comment]
This is possible if you're willing to make Node.js a prerequisite of the package: https://github.com/vega/vega

**Comment by randyzwitch** [comment]
It's also a browser method in the bleeding edge version of vega

https://github.com/vega/vega/releases/tag/v2.2.4

So I think this is possible, it's just all about when I get around to it.

**Comment by tbreloff** [comment]
Is this tool packaged within Vega.jl?

   - *vg2png*: vg2png [-b basedir] vega_json_file [output_png_file]

**Comment by randyzwitch** [comment]
Depends on your definition, but yes it is open-source and freely available. It's not required for rendering anything in Vega.jl right now (that is pure JavaScript).

**Comment by randyzwitch** [comment]
Is a 'soft dependency' a thing? It's easy to find out if node is installed:

```julia
julia> run(`node --version`)
v0.12.7

julia> run(`npm version`)
{ npm: '2.12.1',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.7',
  openssl: '1.0.1p',
  uv: '1.6.1',
  v8: '3.28.71.19',
  zlib: '1.2.8' }
```

This functionality doesn't feel like one where I would want to install node on people's computers, just so they could save if they wanted to via a function (instead of say, just taking a screenshot, which is already possible). 

So is just a note in the documentation or throwing a warning if someone calls a `save` function without node installed enough?

**Comment by tbreloff** [comment]
Requiring node for this seems excessive, so I would just warn/error with a
good message.  For me, I'll care about it mainly for generating
documentation for Plots.jl, so a hacky solution would be fine for me.  (for
example, to generate the UnicodePlots.jl examples automatically I had to
hack a screenshot on a hardcoded part of the screen)

**Comment by randyzwitch** [comment]
Cool. Have an open ticket at vega source b/c their utilities don't work quite right; assuming they get back to me quickly it should be a pretty easy feature to add SVG/PNG and maybe PDF.

**Comment by randyzwitch** [comment]
Just so I don't forget:

https://github.com/vega/vega/issues/356

**Comment by randyzwitch** [comment]
I think this is a nightmare calling out to Node. You've got to have Cairo versions just right (there's a bug in the current version from homebrew), you have to call `npm install` to get the dependencies for the scripts (unless I commit them into the package directly).

Not saying I'm not going to do this, but it might be a little bit. In the meantime, here's a fun picture of the bug in Cairo:

![a42c410e-5ad5-11e5-83bc-f66e453171a5](https://cloud.githubusercontent.com/assets/2762787/9878020/6e26339e-5b8e-11e5-9d3a-34960d1fc74c.png)

**Comment by tbreloff** [comment]
What bug? Looks good to me.  Perfectly readable.

**Comment by randyzwitch** [comment]
Rather than do all sorts of complicated node requirements or other business, I tackled this with pure JavaScript by injecting a link that references the graph. I think this is unobtrusive, but please pull from master and test/offer suggestions. 

This is way easier than writing a function to do this, since I would either need phantomjs or node to render the graph; here the graph is already rendered, and if you like it, download it.

![screen shot 2015-09-29 at 12 50 55 pm](https://cloud.githubusercontent.com/assets/2762787/10171565/c5c92870-66a8-11e5-9797-bfbb5e181009.png)

(The downloaded PNG doesn't have the link in it, I only select the canvas for downloading)
