### ISSUE TITLE
Add background color to plots

### ISSUE THREAD

**Issue by cndesantana** [johnmyleswhite/Vega.jl#81]
Hi,

All the figures I generate with Vega.jl have a transparent background. Is it supposed to be like that? Is there a way to add a background color to my plots (e.g. white background).? 

Thanks

**Comment by randyzwitch** [comment]
Thanks for finding this, it's great having a real-world user running the package through its paces! 

Turns out that the core Vega.js documentation didn't contain this property, but it exists. In a second, I'll push a fix to master.

```julia
x = [1, 2, 3, 4, 5]
y = [1, 2, 3, 2, 1]

a = barplot(x = x, y = y)

a.background = "green"

a

```
![download 1](https://cloud.githubusercontent.com/assets/2762787/11324436/d471cbbc-90ff-11e5-97c4-d8e1a4a24c3d.png)

![download](https://cloud.githubusercontent.com/assets/2762787/11324437/dafaa7c4-90ff-11e5-9a6e-cd3e717753d5.png)

**Comment by randyzwitch** [comment]
Ok, now you can use `Pkg.checkout("Vega")` and set the background color to white (or whatever you want)

**Comment by cndesantana** [comment]
Hi,

Thanks a lot! Works like a charm! :)

Charles
________________________________
