### ISSUE TITLE
heatmap with Float64 values stored in a Data Frame

### ISSUE THREAD

**Issue by cndesantana** [johnmyleswhite/Vega.jl#84]
Hi,

I am facing an error to create a heatmap and I suppose this error can be associated with the type of my X and Y axis data. Please find the following example:

        mydf = DataFrame(d0 = rep(collect(0:0.25:0.75),4), A = [rep(0.0,4);rep(0.25,4);rep(0.5,4);rep(0.75,4)], dc = rand(16))
        julia> hm = heatmap(x = mydf[:d0], y = mydf[:A], color = mydf[:dc])
        ERROR: TypeError: typeassert: expected Array{T,1}, got DataArrays.DataArray{Float64,1}

Do you know a way to use a data frame as an input for heatmap function?

I tried to use the function DataArray within the heatmap function, but I faced the same error:

        julia> hm = heatmap(x = DataArray(mydf[:d0]), y = DataArray(mydf[:A]), color = DataArray(mydf[:dc]))
        ERROR: TypeError: typeassert: expected Array{T,1}, got DataArrays.DataArray{Float64,1}

Thanks!

**Comment by randyzwitch** [comment]
If you do `Pkg.checkout("Vega")` it will work now. I forgot to specify `AbstractArray`, instead putting `Vector`. Computers never seem to know what you mean :)

However, similar to #80 and #32, it's not going to be pretty when it does plot, as I've got the scale data types incorrect. Thanks for pointing these out, because clearly I don't have enough real-world examples yet to harden up these functions.

**Comment by cndesantana** [comment]
Thank you for working in such a nice package! I am trying to avoid generating unnecessary files in my simulations, so I am working more and more with plotting in Julia (as my simulations are already in Julia). I am happy to know that my exploration of Vega.jl features is helping you and your collaborators to make a better package.

Thanks! I will be aware of how issues #80 and #32 evolve.

________________________________

**Comment by randyzwitch** [comment]
Closing in favor of meta issue
